-- Incremental transformation layer: hourly OT features + daily OEE as Dynamic Tables.
-- These are the Snowflake equivalents of src/factorypulse/features.py and oee.py.
USE SCHEMA FACTORYPULSE.OPS;

-- 1) Hourly sensor aggregates per asset (refreshes as new readings land)
CREATE OR REPLACE DYNAMIC TABLE SENSOR_HOURLY
    TARGET_LAG = '5 minutes' WAREHOUSE = COMPUTE_WH
AS
SELECT ASSET_ID,
       DATE_TRUNC('hour', TS)       AS TS_HOUR,
       AVG(VIBRATION_MM_S)          AS VIB_MEAN_1H,
       MAX(VIBRATION_MM_S)          AS VIB_MAX_1H,
       STDDEV(VIBRATION_MM_S)       AS VIB_STD_1H,
       AVG(TEMPERATURE_C)           AS TEMP_MEAN_1H,
       MAX(TEMPERATURE_C)           AS TEMP_MAX_1H,
       AVG(RPM)                     AS RPM_MEAN_1H,
       STDDEV(RPM)                  AS RPM_STD_1H,
       COUNT(*)                     AS N_SAMPLES
FROM SENSOR_READINGS
WHERE MACHINE_STATUS = 'RUNNING'
GROUP BY ASSET_ID, DATE_TRUNC('hour', TS);

-- 2) Model-ready features: rolling windows, baseline ratios and IT context (hours since maintenance)
CREATE OR REPLACE DYNAMIC TABLE ASSET_FEATURES
    TARGET_LAG = '5 minutes' WAREHOUSE = COMPUTE_WH
AS
WITH base AS (
    SELECT ASSET_ID, MEDIAN(VIB_MEAN_1H) AS VIB_BASE, MEDIAN(TEMP_MEAN_1H) AS TEMP_BASE
    FROM SENSOR_HOURLY
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ASSET_ID ORDER BY TS_HOUR) <= 72
    GROUP BY ASSET_ID
),
roll AS (
    SELECT h.*,
           AVG(VIB_MEAN_1H)  OVER (PARTITION BY ASSET_ID ORDER BY TS_HOUR ROWS BETWEEN 5 PRECEDING AND CURRENT ROW)  AS VIB_MEAN_6H,
           AVG(TEMP_MEAN_1H) OVER (PARTITION BY ASSET_ID ORDER BY TS_HOUR ROWS BETWEEN 5 PRECEDING AND CURRENT ROW)  AS TEMP_MEAN_6H,
           AVG(RPM_STD_1H)   OVER (PARTITION BY ASSET_ID ORDER BY TS_HOUR ROWS BETWEEN 5 PRECEDING AND CURRENT ROW)  AS RPM_STD_6H,
           AVG(VIB_MEAN_1H)  OVER (PARTITION BY ASSET_ID ORDER BY TS_HOUR ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS VIB_MEAN_24H,
           AVG(TEMP_MEAN_1H) OVER (PARTITION BY ASSET_ID ORDER BY TS_HOUR ROWS BETWEEN 23 PRECEDING AND CURRENT ROW) AS TEMP_MEAN_24H
    FROM SENSOR_HOURLY h
)
SELECT r.ASSET_ID, r.TS_HOUR,
       r.VIB_MEAN_1H, r.VIB_MAX_1H, r.VIB_STD_1H, r.TEMP_MEAN_1H, r.TEMP_MAX_1H, r.RPM_MEAN_1H, r.RPM_STD_1H,
       r.VIB_MEAN_6H, r.TEMP_MEAN_6H, r.RPM_STD_6H, r.VIB_MEAN_24H, r.TEMP_MEAN_24H,
       r.VIB_MEAN_6H  - LAG(r.VIB_MEAN_6H, 24)  OVER (PARTITION BY r.ASSET_ID ORDER BY r.TS_HOUR) AS VIB_TREND_24H,
       r.TEMP_MEAN_6H - LAG(r.TEMP_MEAN_6H, 24) OVER (PARTITION BY r.ASSET_ID ORDER BY r.TS_HOUR) AS TEMP_TREND_24H,
       r.VIB_MEAN_1H / NULLIF(b.VIB_BASE, 0)  AS VIB_RATIO_BASELINE,
       r.TEMP_MEAN_1H - b.TEMP_BASE           AS TEMP_DELTA_BASELINE,
       COALESCE(DATEDIFF('hour',
            (SELECT MAX(CLOSED_TS) FROM WORK_ORDERS w WHERE w.ASSET_ID = r.ASSET_ID AND w.STATUS = 'CLOSED' AND w.CLOSED_TS <= r.TS_HOUR),
            r.TS_HOUR), 336)                   AS HOURS_SINCE_MAINTENANCE,
       IFF(EXISTS (SELECT 1 FROM FAILURE_EVENTS f WHERE f.ASSET_ID = r.ASSET_ID
                   AND f.FAILURE_TS > r.TS_HOUR AND f.FAILURE_TS <= DATEADD('hour', 24, r.TS_HOUR)), 1, 0) AS LABEL
FROM roll r JOIN base b USING (ASSET_ID);

-- 3) Daily OEE per asset from ERP production orders
CREATE OR REPLACE DYNAMIC TABLE OEE_DAILY
    TARGET_LAG = '1 hour' WAREHOUSE = COMPUTE_WH
AS
SELECT a.PLANT_ID, a.LINE_ID, p.ASSET_ID, p.SHIFT_DATE,
       SUM(p.PLANNED_MINUTES)                                    AS PLANNED_MINUTES,
       SUM(p.RUN_MINUTES)                                        AS RUN_MINUTES,
       SUM(p.UNPLANNED_DOWNTIME_MINUTES)                         AS UNPLANNED_DOWNTIME_MINUTES,
       SUM(p.TOTAL_COUNT)                                        AS TOTAL_COUNT,
       SUM(p.GOOD_COUNT)                                         AS GOOD_COUNT,
       SUM(p.SCRAP_COUNT)                                        AS SCRAP_COUNT,
       SUM(p.RUN_MINUTES) / NULLIF(SUM(p.PLANNED_MINUTES), 0)    AS AVAILABILITY,
       LEAST(1, SUM(p.TOTAL_COUNT * a.IDEAL_CYCLE_SEC / 60) / NULLIF(SUM(p.RUN_MINUTES), 0)) AS PERFORMANCE,
       SUM(p.GOOD_COUNT) / NULLIF(SUM(p.TOTAL_COUNT), 0)         AS QUALITY,
       AVAILABILITY * PERFORMANCE * QUALITY                      AS OEE
FROM PRODUCTION_ORDERS p JOIN ASSETS a USING (ASSET_ID)
GROUP BY a.PLANT_ID, a.LINE_ID, p.ASSET_ID, p.SHIFT_DATE;
